CREATE TABLE IF NOT EXISTS carreras (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  sigla VARCHAR(10) NOT NULL UNIQUE,
  activo TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS turnos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  sigla VARCHAR(5) NOT NULL UNIQUE,
  activo TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS grados (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  numero INT NOT NULL UNIQUE,
  activo TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS grupos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  carrera_id BIGINT NOT NULL,
  turno_id BIGINT NOT NULL,
  grado_id BIGINT NOT NULL,
  consecutivo INT NOT NULL,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT fk_grupo_carrera FOREIGN KEY (carrera_id) REFERENCES carreras(id),
  CONSTRAINT fk_grupo_turno FOREIGN KEY (turno_id) REFERENCES turnos(id),
  CONSTRAINT fk_grupo_grado FOREIGN KEY (grado_id) REFERENCES grados(id),
  CONSTRAINT uq_grupo_comp UNIQUE (carrera_id, turno_id, grado_id, consecutivo)
);

CREATE TABLE IF NOT EXISTS alumnos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  matricula VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(80) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  grupo_id BIGINT NOT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT fk_alumno_grupo FOREIGN KEY (grupo_id) REFERENCES grupos(id)
);
